---
target: local

ferm_ansible_controllers: ['127.0.0.1']
tcpwrappers_controllers: ['127.0.0.1']

mysql_mysqld_allow: [ "ALL" ]
mysql_mysqld_bind_address: '0.0.0.0'

webhost: local
allow_override_htaccess: None

app_env:
  aliases: []
  user: 'vagrant'
  group: 'www-data'
  admin_email: admin@{{ webdomain }}
  fpm_listen: '/var/run/php5-fpm-{{ app_name }}.sock'
  files_tarball_filename: '{{ app_name }}.tar.gz'
  db_dump_filename: '{{ app_name }}.sql.gz'
  db_name: "{{ app_name }}"
  db_user: "{{ app_name }}"
  # Set to True if the target env has memcached available
  memcached: True
  # True clones the cur database
  db_clone: False
  # True looks for a DB dump to upload and import
  db_import: False
  # True syncs with source DB
  db_sync: False
  # True looks for tarballs (files) to upload and import
  files_import: False
  files_sync: False
  files_copy: False
  do_cur_backup: False
  adjust_db: False
  syslog: True

drupal_admin_password: "drups1ble"

# License key
newrelic_license_key: False

