---
- include: core.yml

- name: Gather default and custom facts
  hosts: 'all:!localhost'
  gather_facts: True

- name: Configure default user account mgmt
  hosts: 'all:!localhost'
  roles: 
    - debops.users

- name: sshd
  hosts: debops_sshd
  roles:
    - { role: debops.sshd, tags: sshd, sudo: yes }

- name: APT
  hosts: debops_apt
  roles:
    - { role: debops.apt, tags: apt, sudo: yes }

- name: tcpwrappers
  hosts: debops_tcpwrappers
  roles:
    - { role: debops.tcpwrappers, tags: tcpwrappers, sudo: yes }

- name: MySQL
  hosts: drupsible_mysql
  roles:
    - role: drupsible.mysql
      sudo: yes
      tags: mysql
      mysql_users:
        - name: "{{ app_env['db_user'] }}"
          host: "%"
          state: 'present'
          password: '{{ app_env["db_password"] | default(lookup("password", secret + "/credentials/" + ansible_fqdn + "/mysql/" + app_env.db_user + "/password chars=ascii_letters,digits,hexdigits length=" + mysql_password_length)) }}'
          priv: '{{ app_env["db_name"] }}.*:ALL'
        - name: "{{ app_env['db_user'] }}"
          host: localhost
          state: 'present'
          password: '{{ app_env["db_password"] | default(lookup("password", secret + "/credentials/" + ansible_fqdn + "/mysql/" + app_env.db_user + "/password chars=ascii_letters,digits,hexdigits length=" + mysql_password_length)) }}'
          priv: '{{ app_env["db_name"] }}.*:ALL'
        - name: "{{ app_env['db_user'] }}"
          host: "{{ groups.drupsible_mysql.0 }}"
          state: 'present'
          password: '{{ app_env["db_password"] | default(lookup("password", secret + "/credentials/" + ansible_fqdn + "/mysql/" + app_env.db_user + "/password chars=ascii_letters,digits,hexdigits length=" + mysql_password_length)) }}'
          priv: '{{ app_env["db_name"] }}.*:ALL'

- name: MySQL (for cloned DB mode)
  hosts: drupsible_mysql
  roles:
    - role: drupsible.mysql
      tags: mysql-clone
      sudo: yes
      when: "app_env.db_clone"
      vars:
        mysql_databases:
          - name: "{{ app_name }}_{{ build }}"
            state: 'present'
  
- name: PHP-FPM
  hosts: debops_php5
  roles:
    - { role: debops.php5, tags: php5, sudo: yes, when: "apache2_mpm != 'prefork'" }

- name: Public Key Infrastructure (apache2 group)
  hosts: drupsible_apache2
  roles:
    - role: debops.pki
      tags: pki
      sudo: yes 

- name: Apache
  hosts: drupsible_apache2
  roles:
    - role: drupsible.apache2
      tags: apache2
      sudo: yes
      apache2_pki_crt: "/etc/pki/host/certs/{{ webhost }}.{{ webdomain }}.crt"
      apache2_pki_key: "/etc/pki/host/private/{{ webhost }}.{{ webdomain }}.key"
