---
- include: config.yml

- name: Deploy
  hosts: drupsible_deploy
  roles:
    - role: drupsible.deploy
      tags: deploy
      varnish_mgmt_port: "{{ varnish_mgmt_port }}"
      target: "{{ app_target | default('prod') }}"
      webhost: "{{ app_webhost | default('www') }}"

