---
target: prod

app_name: example-project
webhost: www
webdomain: "example.com"

php_value:
  memory_limit: 192M
  newrelic_appname: "{{ app_name }}"
  max_input_vars: 2000

app_env:
  aliases:
    - "{{ webdomain }}"
  user: example-project
  group: www-data
  fpm_listen: '/var/run/php5-fpm-{{ app_name }}.sock'
  admin_email: "admin@{{ webdomain }}"
  files_tarball_filename: '{{ app_name }}-files.tar.gz'
  db_dump_filename: '{{ app_name }}.sql.gz'
  db_name: "{{ app_name }}"
  db_user: "{{ app_name }}"
  # Set to True if the target env has memcached available
  memcached: True
  # True clones the cur database
  db_clone: False
  # True looks for a DB dump to upload and import
  db_import: False
  # True syncs with source DB
  db_sync: False
  # True looks for tarballs (files) to upload and import
  files_import: False
  files_sync: False
  files_copy: True
  do_cur_backup: True
  adjust_db: True
  syslog: yes

sshd_custom_options: |
  # Drupsible - disable DNS lookups and negotiation of slow GSSAPI
  UseDNS no
  GSSAPIAuthentication no
