php5_packages:
  - php-pear
  - php-soap
  - php5-curl
  - php5-gd
  - php5-gmp
  - php5-mcrypt
  - php5-memcached
  - php5-mysql

php5_post_max_size: '32M'

php_value:
  memory_limit: 192M
  newrelic_appname: "{{ app_name }}"
  max_input_vars: 2000
