---
# Self-signed certs
pki_certificates:
  - cn: "{{ webdomain }}"
    source: "hosts/{{ app_webhost | default('www') }}.{{ webdomain }}/host"
    destination: 'host'
    filename: "{{ app_webhost | default('www') }}.{{ webdomain }}"
pki_routes:
  - name: "host_{{ webdomain }}"
    authority: 'ca/internal/certs'
    realm: "hosts/{{ app_webhost | default('www') }}.{{ webdomain }}/host/certs"
    file: "{{ app_webhost | default('www') }}.{{ webdomain }}.crt"
