---
- name: Gather default and custom facts
  hosts: 'all:!localhost'
  gather_facts: True

# Install/maintain a Drupal site. 
- name: MySQL
  hosts: drupsible_mysql
  roles:
    - { role: drupsible.mysql, tags: mysql, sudo: yes }

- name: Memcached
  hosts: drupsible_memcached
  roles:
    - { role: drupsible.memcached, tags: memcached, sudo: yes }

- name: New Relic
  hosts: drupsible_newrelic
  roles:
    - { role: drupsible.newrelic, tags: newrelic, sudo: yes }

- name: Web Server
  hosts: drupsible_apache2
  roles:
    - { role: drupsible.apache2, tags: apache2, sudo: yes }

- name: Deploy
  hosts: drupsible_deploy
  roles:
    - { role: drupsible.deploy, tags: deploy }
