---
- src: https://github.com/debops/ansible-core
  version: remotes/origin/v0.1.1
  name: debops.core
- src: https://github.com/debops/ansible-pki
  version: master
  name: debops.pki
- src: https://github.com/debops/ansible-bootstrap
  version: remotes/origin/v0.1.0
  name: debops.bootstrap
- src: https://github.com/debops/ansible-postfix
  version: master
  name: debops.postfix
- src: https://github.com/debops/ansible-sshd
  version: remotes/origin/v0.2.1
  name: debops.sshd
- src: https://github.com/mbarcia/drupsible-apache
  version: remotes/origin/0.9
  name: drupsible.apache2
- src: https://github.com/mbarcia/drupsible-memcached
  version: remotes/origin/0.9
  name: drupsible.memcached
- src: https://github.com/mbarcia/drupsible-samba
  version: remotes/origin/0.9
  name: drupsible.samba
- src: https://github.com/mbarcia/drupsible-newrelic
  version: remotes/origin/0.9
  name: drupsible.newrelic
- src: https://github.com/mbarcia/drupsible-composer
  version: remotes/origin/0.9
  name: drupsible.composer
- src: https://github.com/mbarcia/drupsible-drush
  version: remotes/origin/0.9
  name: drupsible.drush
- src: https://github.com/mbarcia/drupsible-mysql
  version: remotes/origin/0.9
  name: drupsible.mysql
- src: https://github.com/mbarcia/drupsible-deploy
  version: remotes/origin/0.9
  name: drupsible.deploy
- src: https://github.com/mbarcia/drupsible-varnish
  version: remotes/origin/0.9
  name: drupsible.varnish
